### ISSUE TITLE
Question about what the expected output should be..

### ISSUE THREAD

**Issue by langley** [ryancrum/json-pretty-print.el#1]
I'd love this: 
{"facets":{"data":{"date_histogram":{"field":"timeStamp","interval":"hour"},"facet_filter":{"range":{"timeStamp":{"from":"2013-04-21T00:00:00","to":"2013-04-21T23:59:59"}}}}}}

to print as json-lint does... e.g. 
{
    "facets": {
        "data": {
            "date_histogram": {
                "field": "timeStamp",
                "interval": "hour"
            },
            "facet_filter": {
                "range": {
                    "timeStamp": {
                        "from": "2013-04-21T00:00:00",
                        "to": "2013-04-21T23:59:59"
                    }
                }
            }
        }
    }
}

However even though I ~think~ I have json-pretty print installed properly, all it does is print the input on the same line... 

Is that the expected behavior? 

Thanks in advance! I would LOVE to work with JSON in emacs, particularly to work with elasticsearch

**Comment by ryancrum** [comment]
Hi @langley,

This code has actually been merged into emacs trunk, so in future version of Emacs it will be included "out of the box". See: http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/json.el?h=trunk

If you want to use this code, make sure you also have my "special" version of [json.el](https://raw.github.com/thorstadt/json.el/master/json.el) loaded, and you should get what you're looking for with json-pretty-print. To be honest, it's probably just less effort to install the json.el from Emacs trunk and forget about json-pretty-print.el altogether.

Thanks,
-Ryan
